-- Disabled: minuet-ai.nvim is not currently used.
-- local function gh(repo) return 'https://github.com/' .. repo end
-- vim.pack.add { gh 'milanglacier/minuet-ai.nvim', gh 'nvim-lua/plenary.nvim' }
